version : "3.5"

networks:
        inception-network:

volumes:
        mariadb-volume:
                driver_opts:
                       device: /home/tkomaris/data/mariadb
                       o: bind
                       type: volume

        wordpress-volume:
                driver_opts:
                       device: /home/tkomaris/data/wordpress
                       o: bind
                       type: volume

services:
        nginx:
                build: requirements/nginx
                container_name: nginx # Name
                ports: 
                        - "443:443"
                restart: unless-stopped
                networks:
                        - inception-network
                env_file:
                        - .env
                volumes:
                        - wordpress-volume:/var/www/wordpress

        mariadb:
                build: requirements/mariadb
                container_name: mariadb
                ports: 
                        - "3306:3306"
                restart: unless-stopped
                networks:
                        - inception-network
                env_file:
                        - .env
                volumes:
                        - mariadb-volume:/var/lib/mysql
        
        wordpress:
                depends_on:
                        - mariadb
                build: requirements/wordpress
                container_name: wordpress
                ports:
                        - "9000:9000"
                restart: unless-stopped
                networks:
                        - inception-network
                env_file:
                        - .env
                volumes:
                        - wordpress-volume:/var/www/wordpress
